export const BLOG_POSTS = [
  { slug: "kapsulyarnoe-narashchivanie-chto-eto", title: "Капсульное наращивание волос: что это, как держится и сколько стоит", description: "Разбираю самый популярный метод: горячий кератин, сколько капсул нужно, как долго держится.", date: "2025-04-10", tag: "Капсульное", readTime: "5 мин", popular: true },
  { slug: "bioproteinovye-volosy-novoe-pokolenie", title: "Биопротеиновые волосы нового поколения: без ламинирования и кератина", description: "Почему биопротеин лучший выбор для пористых волос. Не требует кератинового ламинирования.", date: "2025-04-18", tag: "Биопротеин", readTime: "4 мин", popular: true },
  { slug: "skolko-kapsul-nuzhno", title: "Сколько капсул нужно для наращивания: полный расчёт по типу волос", description: "50 или 300 капсул? Объясняю как рассчитать количество для загущения, удлинения и коррекции.", date: "2025-05-01", tag: "Калькулятор", readTime: "6 мин", popular: true },
  { slug: "korrektsiya-narashchennykh-volos", title: "Коррекция нарощенных волос: когда делать и сколько стоит", description: "Коррекция раз в 2-2,5 месяца. От 160 BYN.", date: "2025-05-05", tag: "Уход", readTime: "4 мин", popular: false },
  { slug: "zagushchenie-bez-udlineniya", title: "Загущение без удлинения: как получить объём и не переплачивать", description: "Загущение биопротеиновыми волосами даёт потрясающий эффект за меньшие деньги.", date: "2025-05-10", tag: "Загущение", readTime: "3 мин", popular: false },
  { slug: "uhod-za-narashhennymi-volosami", title: "Уход за нарощенными волосами: гайд чтобы носить 4-5 месяцев", description: "Какие шампуни нельзя, как расчёсывать, спать, мыть голову.", date: "2025-05-12", tag: "Уход", readTime: "7 мин", popular: true },
  { slug: "slavyanskie-volosy-vs-kitajskie", title: "Натуральный славянский волос: в чём разница и почему это важно", description: "Почему я работаю только с натуральным волосом.", date: "2025-05-14", tag: "О волосах", readTime: "5 мин", popular: false },
  { slug: "mozhno-li-narashchivat-tonkie-volosy", title: "Можно ли наращивать тонкие и ломкие волосы", description: "Разбираю какой метод подходит для тонких волос.", date: "2025-05-15", tag: "Капсульное", readTime: "4 мин", popular: false },
];
